apiVersion: v1
kind: Service
metadata:
  name: backend-feed-service
spec:
  selector:
    app: backend-feed
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Can be changed to NodePort or LoadBalancer depending on needs