apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: nguyentuanbkhn/reverseproxy:v1  # Replace with Docker image link on Docker Hub 
        ports:
        - containerPort: 8080
        resources:                        # Add this section to set resource requirements and limits
          requests:
            cpu: "100m"                  # Minimum CPU requirements (100 milliCPU)
          limits:
            cpu: "500m"                  # Maximum CPU limit (500 milliCPU)
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key
