apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-service
spec:
  selector:
    app: udagram-reverseproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # To access the reverse proxy from outside