language: minimal

services:
  - docker

before_script:
  - docker --version

script:
  # Build Docker images for each service
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  
  # Tag images before pushing to DockerHub
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy:v1
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1

  # Log into DockerHub using information from environment variable
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  # Push Docker images to DockerHub
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/reverseproxy:v1
  - docker push $DOCKER_USERNAME/udagram-frontend:v1