apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
spec:
  selector:
    app: udagram-frontend
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: LoadBalancer  # Depends on how you want to access the frontend